<div class="alert alert-info">
<font size="5"><b>Комментарий ревьюера</b></font>

Привет Евгений! Меня зовут Марат, и я буду твоим ревьюером. Спешу сообщить что все ключевые этапы в работе выполнены,  с задачей тебе удалось справиться. По поводу обращения - в IT сфере принято общаться на «ты» :) Но, если привычней на «вы», дай знать. Как ревьюера моя задача помочь тебе в развитии, дав хорошие советы. Я внимательно посмотрю твой код, ознакомлюсь с твоими выводами и оставлю комментарии. Где то могу предложить небольшие исправление в коде, но ненавязчиво. Где потребуются уточнения, я оставлю много наводящих вопросов. Они помогут тебя с поиском верного решения.

Все мои комментарии размечены по цветам, для лучшего восприятия. 
    
<div class="alert alert-success">Зеленым цветом и 👍, словом «Успех» отмечены особо удачные и элегантные решения, которыми ты можешь гордиться. </div>
        
<div class="alert alert-warning">Желтым и 🤔, словом «Совет», помечены решения у которых есть альтернативные решения, более оптимальные. Ты можешь найти их сразу и доработать проект, или отложить это на потом, для будущих проектах. Проект будет принят и без их доработки. </div>
        
<div class="alert alert-danger"> Красным цветом и значком ❌, словом «Ошибка» помечу твои решения, на которые стоит обратить внимание прежде всего. После их доработки проект будет принят. </div>
        
Залог успеха - работа сообща, взаимное уважение и работа в диалоге. Поэтому, помечай свои ответные комментарии на мои реплики заметным цветом или курсивом, так мне будет легче их отслеживать. Пожалуйста, не изменяй и не удаляй мои комментарии. Все это поможет выполнить повторную проверку быстрей.

</div>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Вывод-к-первому-разделу" data-toc-modified-id="Вывод-к-первому-разделу-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Вывод к первому разделу</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span><ul class="toc-item"><li><span><a href="#Вывод-ко-второму-разделу" data-toc-modified-id="Вывод-ко-второму-разделу-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Вывод ко второму разделу</a></span></li></ul></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span><ul class="toc-item"><li><span><a href="#Вывод-к-четвёртому-разделу" data-toc-modified-id="Вывод-к-четвёртому-разделу-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Вывод к четвёртому разделу</a></span></li></ul></li><li><span><a href="#Общий-вывод" data-toc-modified-id="Общий-вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Общий вывод</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Необходимо защитить данные клиентов страховой компании «Хоть потоп». 

Цель исследования: разработать и обосновать такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию, при этом не ухудшив качество моделей машинного обучения.

Подбирать наилучшую модель не требуется.

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:


Вступление в работу очень важно, так человек, который смотрит твой проект (и на работе в том числе) будет сразу введен в курс дела.





</div>

## Загрузка данных

In [1]:
# импорт библиотек

import pandas as pd
import numpy as np

from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
# чтение файла с разных источников

try:
    ins = pd.read_csv('/datasets/insurance.csv')
except:
    ins = pd.read_csv('C:/Users/Evgenii/Downloads/DS Yandex/Projects/insurance.csv')

ins.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Молодец что используешь конструкцию try - except (if - else), этим ты проявляешь уважение к тем кто будет работать с твоим кодом.

</div>

In [3]:
# переименуем колонки на латиницу

ins.columns = ['gender', 'age', 'salary', 'fam_members', 'benefits']
ins.head()

gender   age   salary  fam_members  benefits
0       1  41.0  49600.0            1         0
1       0  46.0  38000.0            1         1
2       0  29.0  21000.0            0         0
3       0  21.0  41700.0            2         0
4       1  28.0  26100.0            0         0

In [4]:
# информация о типе данных и пропусках
ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   gender       5000 non-null   int64  
 1   age          5000 non-null   float64
 2   salary       5000 non-null   float64
 3   fam_members  5000 non-null   int64  
 4   benefits     5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [5]:
# познакомимся с уникальными значениями столбцов и их количеством
for col in ins.columns:
    print(f'Уникальные значения в столбце {col} (максимум 50): {sorted(ins[col].unique())[:50]}')
    print(f'Число уникальных в {col}: {ins[col].nunique()}')
    print()

Уникальные значения в столбце gender (максимум 50): [0, 1]
Число уникальных в gender: 2

Уникальные значения в столбце age (максимум 50): [18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 65.0]
Число уникальных в age: 46

Уникальные значения в столбце salary (максимум 50): [5300.0, 6000.0, 7400.0, 8900.0, 9800.0, 10000.0, 10600.0, 10800.0, 11000.0, 11200.0, 11300.0, 12200.0, 12900.0, 13000.0, 13200.0, 13300.0, 13400.0, 13500.0, 13800.0, 13900.0, 14100.0, 14300.0, 14400.0, 14500.0, 14600.0, 14700.0, 15000.0, 15100.0, 15200.0, 15600.0, 15700.0, 15900.0, 16000.0, 16200.0, 16300.0, 16400.0, 16500.0, 16600.0, 16700.0, 17000.0, 17100.0, 17300.0, 17400.0, 17500.0, 17600.0, 17700.0, 17800.0, 17900.0, 18100.0, 18200.0]
Число уникальных в salary: 524

Уникальные значения в столб

In [6]:
# общее представление о данных: минимальное, максимальное, среднее
ins.describe()

gender          age        salary  fam_members     benefits
count  5000.000000  5000.000000   5000.000000  5000.000000  5000.000000
mean      0.499000    30.952800  39916.360000     1.194200     0.148000
std       0.500049     8.440807   9900.083569     1.091387     0.463183
min       0.000000    18.000000   5300.000000     0.000000     0.000000
25%       0.000000    24.000000  33300.000000     0.000000     0.000000
50%       0.000000    30.000000  40200.000000     1.000000     0.000000
75%       1.000000    37.000000  46600.000000     2.000000     0.000000
max       1.000000    65.000000  79000.000000     6.000000     5.000000

In [7]:
# проверка на мультиколлинеарность
ins.corr()

gender       age    salary  fam_members  benefits
gender       1.000000  0.002074  0.014910    -0.008991  0.010140
age          0.002074  1.000000 -0.019093    -0.006692  0.651030
salary       0.014910 -0.019093  1.000000    -0.030296 -0.014963
fam_members -0.008991 -0.006692 -0.030296     1.000000 -0.036290
benefits     0.010140  0.651030 -0.014963    -0.036290  1.000000

### Вывод к первому разделу 

*В данных страховой компании собрана персональная информация о 5000 клиентах-физических лицах в разрезе их пола, возраста, зарплаты, количества членов семьи (признаки). В последней колонке указано количество страховых выплат клиенту за последние 5 лет (целевой признак).*

*Пропусков в данных не имеется, аномальных значений тоже. Имеется прямая не очень сильная корреляция между возрастом и страховыми выплатами (коэффициент 0.65), однако, признак в любом случае значимый. Персональные данные (признаки) необходимо зашифровать, чтобы качество моделей машинного обучения не ухудшилось.*

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍: 
    
EDA проведено.  


- Здорово чтоб поработала с типами данных 
    
    
    
<div class="alert alert-warning">


Совет 🤔: 
    
    
- У тебя есть проверка на мультиколлинеарность, а какие 2 типа проблемы вызывает она и для каких моделей, и почему для данного проекта было бы интересно на нее глянуть? 

</div>



<font color='purple'><b>Комментарий студента</b></font><br>
<font color='purple'>Добрый день, Марат! Благодарю за проверку проекта. Постараюсь немного улучшить.)<br>Насколько знаю, мультиколлинеарность влияет на линейные модели, в нашем случае модель линейной регрессии. Либо 2 признака сильно коррелируют, и тогда один из них лучше убрать для повышения качества предсказаний, либо признак с целевым признаком коррелируют, и тогда дата лик скорее всего. Также желательно удалить, а то теряется смысл в модели, можно же по одному признаку легко предсказания делать. Но надо смотреть на значимость признака, а также на их общее число. Обычно мультиколлинеарность выявляется при коэф. корреляции более чем 0.9 по модулю.</font>

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюераV2</b></font>

Успех 👍:

 
- Дополню:

Первый момент: да, мультиколлиниарность проблема линейных моделей - могут переобучаться.... теоретически. Но в логистической, и в линейной регрессиях (когда мы решаем оптимизационно, а не аналитически) реализована регуляризация, которая решает проблему мультиколлиниарности признаков. "Деревянные" модели (RF, DT) устойчивы к мультиколлинеарности, а кластеризация тоже почти не зависит от линейных зависимостей. Получается, избавляться от мультиколлинеарности чтобы не переобучаться не обязательно )) 
    
Второй момент: интерпретируемость линейной модели (мы по коеффициентам судим как признаки влияют на таргет), тут  мультиколлинеарность надо убирать. Самый простой дроп одного из признаков из каждой пары

    
 - Для нашего проекта это мультиколлинеарность можно глянуть, потому что у нас как раз линейная модель, которую мы решаем аналитически (то есть без всяких ругуляризаций и градиентных спусков). Это возникает потому что в случае высокой корреляции матрица $𝑋^𝑇*𝑋$  близка к вырожденной, как результат чувствительность к малейшему изменению входных данных, приводящая к сильному изменению весов модели, вот остюда и переобучение и  теряется интерпретируемость. И если бы была мультиколлинеарность то можно было подумать как ее убрать (хотя на решение задачи нашего проекта мультиколлинеарность бы не повлияла).  Но ее нет, корреляция ниже 0,75-0,8. Может и с 0,9, честно говоря точную цифру не знаю, разные видел версии )  
  
</div>



## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

In [8]:
# разделение на признаки и целевой признак

features = ins.drop(columns='benefits')
target = ins['benefits']
print(features.shape)
print(target.shape)

(5000, 4)
(5000,)


*Для большей наглядности при последующей проверке формул линейной регрессии в этом разделе будем использовать **весь** датасет для обучения-предсказания, без разделения на обучающую-тестовую выборки.*

In [9]:
# создание класса линейной регрессии по формуле регрессии

class LinearRegressionFormula:
    def __init__(self, train_features, train_target):
        
        # добавление столбца из единиц для расчёта сдвига w0
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1) 
        y = train_target
        w = np.linalg.inv(X.T @ X) @ X.T @ y # расчёт вектора весов и сдвига
        self.w = w[1:] # веса
        self.w0 = w[0] # сдвиг
        
    # функция предсказаний по формуле линейной регрессии
    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0 
    
# инициализация класса по исходным данным, функция предсказаний и метрика
model = LinearRegressionFormula(features, target)
predictions = model.predict(features)
print(r2_score(target, predictions))

0.42494550286668


In [10]:
# вывод предсказаний по исходным данным
predictions

0       0.511727
1       0.684316
2       0.093734
3      -0.222589
4       0.065084
          ...   
4995    0.028390
4996    0.253367
4997   -0.256970
4998   -0.190992
4999    0.049050
Length: 5000, dtype: float64

In [11]:
# веса модели по предсказаниям исходных данных
model.w

array([ 7.92580543e-03,  3.57083050e-02, -1.70080492e-07, -1.35676623e-02])

In [12]:
# сдвиг по предсказаниям исходных данных
model.w0

-0.9382355041524769

In [13]:
# генерация матрицы-ключа, с проверкой на обратимость

while 1>0:
    P = np.random.randint(1, 101, size=(features.shape[1], features.shape[1]))
    
    try:
        np.linalg.inv(P)
        break
        
    except:
        continue
print(P)

[[ 5 20  9 52]
 [73 95 76 18]
 [31 99  7 59]
 [95 31 76  5]]


In [14]:
# инициализация класса по шифрованным данным, функция предсказаний и метрика

model_2 = LinearRegressionFormula(features @ P, target)
predictions_2 = model_2.predict(features @ P)
print(r2_score(target, predictions_2))

0.42494550286663024


In [15]:
# суммарная разность предсказаний по исходным и шифрованным данным
(predictions_2 - predictions).abs().sum()

0.00046454798699080424

In [16]:
# веса модели по предсказаниям шифрованных данных
model_2.w

array([-1.25966709e-03,  3.53154592e-04,  1.25726823e-03, -7.98927557e-05])

In [17]:
# сдвиг по предсказаниям шифрованных данных
model_2.w0

-0.938235458095396

**Ответ:** Качество линейной регрессии не изменится, если признаки умножить на обратимую квадратную матрицу размерностью по числу признаков, то есть предсказания по исходным признакам и признакам после умножения на матрицу будут идентичными. 

**Обоснование:** 

Поскольку мы домножаем исходную матрицу $X$ на матрицу $P$, то новые предсказания будут выражаться как $a' = XP w'$.

Исходные предсказания: $a = X w$ . Докажем, что  новые и исходные предсказания равны, то есть $XP w' = X w$.


Формула обучения исходных данных: $w = (X^T X)^{-1} X^T y$. 

Формула обучения новых данных (умножаем $X$ на $P$): $w' = ((X P)^T (X P))^{-1} (X P)^T y$. 

Упростим последнее выражение.

** **


$w' = (P^T X^T X P)^{-1} (P^T X^T) y$, так как по свойству транспонированной матрицы $(A B)^T = B^T A^T$

$w' = (P^T (X^T X) P)^{-1} (P^T X^T) y$, выделяем 3 квадратные матрицы: $P^T$, $X^T X$ и $P$

$w' = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y$, так как $(A B C)^{-1} = (A (B C))^{-1} = (B C)^{-1} A^{-1} = C^{-1} B^{-1} A^{-1}$, свойство применимо только для квадратных матриц

$w' = P^{-1} (X^T X)^{-1} E X^T y$, так как $A^{-1} A = E$ , а $P^T$ - квадратная матрица

$w' = P^{-1} (X^T X)^{-1} X^T y$, так как $A E = A$, при этом у $E$ размерность по числу признаков (из-за матриц  $P^T$ и $(P^T)^{-1}$), а $(X^T X)^{-1}$ квадратная матрица и также размерностью в число признаков

** **

Подставляем $w$ и $w'$ в предполагаемое равенство $XP w' = X w$:

$X P P^{-1} (X^T X)^{-1} X^T y = X (X^T X)^{-1} X^T y$

$X E (X^T X)^{-1} X^T y = X (X^T X)^{-1} X^T y$, так как $A A^{-1} = E$, а $P$ - квадратная матрица

$X (X^T X)^{-1} X^T y = X (X^T X)^{-1} X^T y$, так как $E A = A$, при этом у $E$ размерность по числу признаков (из-за матриц  $P$ и $P^{-1}$), а $(X^T X)^{-1}$ квадратная матрица и также размерностью в число признаков

$X (X^T X)^{-1} X^T y = X (X^T X)^{-1} X^T y$

Получили явное тождество, следовательно, предсказания до и после умножения матриц равны, соответственно, метрики по исходным и предсказанным данным тоже равны.

** **

Выведем также зависимость весов линейной регрессии до и после умножения матриц.

$w' = P^{-1} (X^T X)^{-1} X^T y$

$w' = P^{-1} (X^T X)^{-1} X^T X w$, так как предсказание это $X w$

$w' = P^{-1} (X^T X)^{-1} (X^T X) w$

$w' = P^{-1} E w$, так как $A^{-1} A = E$ , а $X^T X$ - квадратная матрица

$w' = P^{-1} w$, так как $A E = A$, а  $P^{-1}$ квадратная матрица размерностью в число признаков, как и $X^T X$


<div class="alert alert-danger">
<font size="5"><b>Комментарий ревьюера</b></font>

Ошибка ❌:
    
    
Направление твоего доказательства верное - берем формулу, подставляем, немножко математической магии: открываем скобки, сокращаем итп итд, как в обычной арифметике и вуаля! Вообще тут много аналогий:  в "мире матриц" умножив единичную матрица на вектор или матрицу получаем тот же самый вектор или матрицу, в "мире цифр" это как умножив число на 1, получить тоже самое число. Если умножить матрицу на обратную ей матрицу получаем единичную матрицу, точно также если умножить число на обратное ей число получаем единицу. Но есть особенности пробразований в "мире матриц" которые надо учитывать: обратная матрица существует только у квадратной матрицы, поэтому:  
    
$$
(AB)^{-1} = B^{-1} A^{-1}
$$
    
только когда у нас A и B квадратные, Может когда то в линейную алгебру введут "мнимые матрицы", по подобию "мнимых чисел" )) Но пока не ввели, поэтому перепрыгивать через этот момент не можем, это как на ноль делить
      



И маленькая подсказка, найди тут:
    
$$
((XP)^T XP)^{-1}
$$
  
    
три квадратные матрицы. Зачем, спросишь ты, нам 3 матрицы под знаком обратной матрицы (-1), а ты найди под -1 три квадратные матрицы, чтобы можно будет раскрыть скобку, по правилу:
    
    
$$
(ABС)^{-1} = ((AB)С)^{-1} = ((AB)С)^{-1} = С^{-1}(AB)^{-1} = С^{-1}B^{-1}A^{-1}
$$          
    
</div>



<font color='purple'><b>Комментарий студента</b></font><br>
<font color='purple'>Да, терзали меня сомнения по поводу некорректности обратных прямоугольных матриц, но посчитал, что это типа что-то комплексных чисел, которые при умножении могут дать целое число.<br>
Доказательство исправил, после поиска квадратных матриц всё пошло легко)  </font>

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюераV2</b></font>



Успех 👍:



А теперь математическая магия применена верно )



</div>


In [18]:
# проверка формулы весов шифрованных данных

print("Веса шифрованных данных, по формуле из весов нешифрованных данных: \n", np.linalg.inv(P) @ model.w) 
print()
print("Веса шифрованных данных, по классической формуле обучения: \n", model_2.w)

Веса шифрованных данных, по формуле из весов нешифрованных данных: 
 [-1.25966801e-03  3.53154085e-04  1.25726947e-03 -7.98915667e-05]

Веса шифрованных данных, по классической формуле обучения: 
 [-1.25966709e-03  3.53154592e-04  1.25726823e-03 -7.98927557e-05]


### Вывод ко второму разделу 

*Произведено шифрование признаков персональных данных путём умножения матрицы объекты-признаки на случайно сгенерированную квадратную матрицу-ключ ($P$) размерностью по числу признаков. Таким образом, получили зашифрованную матрицу объекты-признаки.*

*С помощью формулы линейной регрессии ($a = Xw$, где $a$ - предсказания, $X$ - матрица объекты-признаки, $w$ - веса линейной регрессии) проверено качество предсказания страховых выплат как по исходным данным, так и по зашифрованным. Веса были рассчитаны по формуле обучения $w = (X^T X)^{-1} X^T y$, где $y$ - вектор целевого признака. Предсказания и, соответственно, метрика R2 (коэффициент детерминации) получились идентичными.*

*Проведено математическое доказательство равенства предсказаний, полученных опытным путём ранее: $XP w' = X w$ , где $XP$ - зашифрованная матрица, а $w'$ - веса линейной регрессии по зашифрованным данным.*

*Также выявлена зависимость весов линейной регрессии у зашифрованной матрицы от весов линейной регрессии исходной матрицы: 
$w' = P^{-1} w$. (надо умножить обратную матрицу-ключ на вектор весов линейной регрессии исходной матрицы).*

## Алгоритм преобразования

**Алгоритм**

*Зафиксируем алгоритм шифрования исходных данных, с проверкой качества линейной регрессии как на шифрованных, так и на исходных данных:*

*1. Генерируем матрицу (с помощью randint, normal, вручную и т.д.) размерностью n на n, где n - число признаков исходного датасета*

*2. Проверяем матрицу на обратимость. Если необратима, повторяем п.1*

*3. Умножаем матричным умножением матрицу объекты-признаки на сгенерированную матрицу. Получаем зашифрованную матрицу данных той же размерности, что и матрица объекты-признаки.*

*4. Разделяем как зашифрованную матрицу, так и целевой признак на обучающую-тестовую выборки, проводим масштабирование данных, инициализируем линейную регрессию, обучаем модель на обучающих данных, делаем предсказания на тестовых данных, считаем метрику R2.* 

*5. Исходный незашифрованный датасет признаков делим на обучающую-тестовую выборки согласно индексации зашифрованного датасета, проводим масштабирование данных, инициализируем линейную регрессию, обучаем модель на обучающих данных, делаем предсказания на тестовых данных, считаем метрику R2.* 

*6. Сравниваем как метрики R2, так и предсказания у зашифрованного и незашифрованного датасетов. Метрики и предсказания должны быть одинаковыми.*

*7. Раскодируем зашифрованную матрицу путём матричного умножения на обратную матрицу-ключ из пункта 1.*


<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:


Все верно.



</div>

**Обоснование**

*1. Матрица $P$ размером (число признаков)  x  (число признаков).*

*2. Если матрица необратима, то шифровать данные нельзя, так как доказательство равенства предсказываемых признаков построено на свойствах обратимых матриц. Да и расшифровать данные будет невозможно.*

*3. Матрица $XP$ размером (число объектов  x  число признаков)*

*4. Согласно постулатов машинного обучения, обучение и предсказания проводят на разных выборках. Масштабирование признаков также желательно для линейной регрессии.* 

*5. Для совпадения всех объектов и чистоты эксперимента необходимо незашифрованный датасет поделить на обучающую и тестовую выборки в том же порядке, что в зашифрованном датасете.*

*6. Предсказания зашифрованного и незашифрованного датасета равны ($XP w' = X w$), это доказано в предыдущем разделе. Вектор целевого признака всегда неизменен, значит и метрика R2 (коэффициент детерминации), зависящая от исходных и предсказанных данных будет одинакова в зашифрованном и незашифрованном датасетах.*

*7. $X = (XP) P^{-1}$ , где $XP$ - зашифрованная матрица, $P$ - матрица-ключ, $X$ - исходная матрица.*


## Проверка алгоритма

In [19]:
# генерирование матрицы-ключа, с проверкой на обратимость

while 1>0:
    P = np.random.randint(1, 101, size=(features.shape[1], features.shape[1]))
    
    if np.linalg.det(P) == 0:
        continue
        
    else:
        break
print(P)

[[10 49 93 68]
 [32 53 82  2]
 [13 56  6 95]
 [18 50 53 65]]





<div class="alert alert-warning">
<font size="5"><b>Комментарий ревьюера</b></font>

Совет 🤔:


    
-   `numpy.randint()` у нас каждый раз генерирует новую матрицу, и для данного проекта по мне так это даже хорошо, ведь каждый раз мы шифруем данные по разному, но на будущее, когда встанет вопрос воспроизводимости результата, помним что для фиксирования рандома используем `numpy.random.seed()`
    
    

</div>


<font color='purple'><b>Комментарий студента</b></font><br>
<font color='purple'>`np.random.seed()` я уже разок использовал в одном из предыдущих проектов. Вот только в данном случае вопрос: если вдруг сгенерируется необратимая матрица, то надо ещё одну попытку осуществить, следовательно `np.random.seed()` надо вставить в блок `else`? Но в таком случае не будет ли ещё одной генерации при следующем запуске кода, так как рандом фиксировали на выходе? А если вставить до генерации, то не будет ли зацикливания при генерации необратимой матрицы?. </font>

<div class="alert alert-warning">
<font size="5"><b>Комментарий ревьюераV2</b></font>



Совет 🤔:


Ну да тут, или while с  гарантированной генерацией обратимой матрицы, или numpy.random.seed(), вместе они не смотрятся. Хотя конечно можно в тело while numpy.random.seed() поставить, но это будет как то на мой взгляд сомнительно. Я уж не говорю что мы можем подобрать такой numpy.random.seed(), что матрица будет обратимой и while вообще не понадобиться. Поэтому мой совет в данном случаи скорее для общей инфомрации получился, а не для практического применения )
</div>


In [20]:
# исходный датасет признаков
features.head()

gender   age   salary  fam_members
0       1  41.0  49600.0            1
1       0  46.0  38000.0            1
2       0  29.0  21000.0            0
3       0  21.0  41700.0            2
4       1  28.0  26100.0            0

In [21]:
# зашифрованный датасет признаков
features_encr = features @ P
features_encr.head()

0          1         2          3
0  646140.0  2779872.0  301108.0  4712215.0
1  495490.0  2130488.0  231825.0  3610157.0
2  273928.0  1177537.0  128378.0  1995058.0
3  542808.0  2336413.0  252028.0  3961672.0
4  340206.0  1463133.0  158989.0  2479624.0

In [22]:
# разделение шифрованных данных на выборки
features_encr_train, features_encr_test, target_train, target_test = train_test_split(
    features_encr, target, test_size=0.25, random_state=12345)

# индексы признаков у зашифрованных данных в обучающей и тестовой выборках
index_features_train = features_encr_train.index
index_features_test = features_encr_test.index

# применим StandardScaler к выборкам
scaler = StandardScaler()
scaler.fit(features_encr_train)
features_encr_train = scaler.transform(features_encr_train)
features_encr_test = scaler.transform(features_encr_test)

<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:

Все правильно, помним о стандартах ML при моделировании


<div>



In [23]:
# признаки у обучающей и тестовой шифрованных данных
print(features_encr_train.shape)
print(features_encr_test.shape)

(3750, 4)
(1250, 4)


In [24]:
# целевые признаки у обучающей и тестовой (не шифруются)
print(target_train.shape)
print(target_test.shape)

(3750,)
(1250,)


In [25]:
# доли классов целевого признака у обучающей
target_train.value_counts(normalize=True)

0    0.885600
1    0.087200
2    0.021600
3    0.003733
4    0.001600
5    0.000267
Name: benefits, dtype: float64

In [26]:
# доли классов целевого признака у тестовой
target_test.value_counts(normalize=True)

0    0.8920
1    0.0768
2    0.0272
3    0.0032
4    0.0008
Name: benefits, dtype: float64

In [27]:
# инициализация, обучение, предсказания, r2 у шифрованных данных

model_encr = LinearRegression()
model_encr.fit(features_encr_train, target_train)
prediction_encr = model_encr.predict(features_encr_test)
r2_encr = r2_score(target_test, prediction_encr)
print(r2_encr)

0.4352275712708723


In [28]:
# разделение признаков исходных данных на выборки по тем же объектам, что и в шифрованных данных

features_train = features.loc[index_features_train, :]
features_test = features.loc[index_features_test, :]
print(features_train.shape)
print(features_test.shape)

(3750, 4)
(1250, 4)


In [29]:
# применим StandardScaler к выборкам исходных данных
scaler.fit(features_train)
features_train = scaler.transform(features_train)
features_test = scaler.transform(features_test)

# инициализация, обучение, предсказания, r2 у исходных данных
model_norm = LinearRegression()
model_norm.fit(features_train, target_train)
prediction_norm = model_norm.predict(features_test)
r2_norm = r2_score(target_test, prediction_norm)
print(r2_norm)

0.43522757127026623


In [30]:
# предсказания по шифрованным данным
prediction_encr

array([0.17494798, 0.80523476, 0.45599281, ..., 0.3129923 , 0.34926113,
       0.7886826 ])

In [31]:
# предсказания по исходным данным
prediction_norm

array([0.17494798, 0.80523476, 0.45599281, ..., 0.3129923 , 0.34926113,
       0.7886826 ])

In [32]:
# декодирование шифрованных данных, приведение данных в читаемый вид

features_decoded = features_encr @ np.linalg.inv(P)
features_decoded = round(features_decoded, 0)
features_decoded = features_decoded.astype(int)
features_decoded.columns = features.columns
features_decoded.head()

gender  age  salary  fam_members
0       1   41   49600            1
1       0   46   38000            1
2       0   29   21000            0
3       0   21   41700            2
4       1   28   26100            0



<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:
    
Все сошлось. Отдельный плюс за: 
    
    
- универсальность кода: код отработает для любой размерности матрицы обьект-признак  

    
- использование конструкции while при проверке на обратимость    
    

- использование train_test_split - все правильно, помним о стандартах ML при моделировании


- использование class LinearRegression, а не готовую библиотечку, где все скрыто, а так все видно и наглядно что полезно при обучении

</div>





### Вывод к четвёртому разделу 

*Произведено программирование алгоритма предыдущего раздела, то есть произведено шифрование признаков матрицей-ключом, с последующим сравнением предсказаний и метрик R2 модели линейной регрессии, взятой из библиотеки sklearn.*

*Как у исходного, так и у шифрованного набора данных получились одинаковыми как вектора предсказаний, так и метрика R2. Шифрованные и исходные данные были разделены на обучающую и тестовую выборки (идентичные по составу объектов в шифрованных и исходных данных), предсказания на тестовых данных получились идентичными.*

*Таким образом, модель LinearRegression из библиотеки sklearn с шифрованным и исходным набором работает идентично программированию линейной регрессии по формуле $a = Xw$, где $a$ - предсказания, $X$ - матрица объекты-признаки, $w$ - веса линейной регрессии.*


## Общий вывод

*Целью исследования являлась разработка метода шифрования персональных данных клиентов страховой компании, чтобы было сложно восстановить исходные данные без ключа, но и не потеряв при этом в качестве машинного обучения. Для реализации цели исследования выполнены следующие задачи:*



 1. **Изучение данных**
 
 
 2. **Доказательство идентичности предсказаний у исходных и шифрованных данных**
 
 
 3. **Построение алгоритма преобразования исходных данных**
  
  
 4. **Проверка алгоритма на модели линейной регресии**
 
 
 
 
 **Задача 1 "Изучение данных"** 


*Данные содержат информацию о 5000 клиентах-физических лицах по признакам пола, возраста, зарплаты, количества членов семьи, а также по целевому признаку (количество страховых выплат за последние 5 лет). Данные без пропусков и аномальных значений.*


**Задача 2 "Доказательство идентичности предсказаний у исходных и шифрованных данных"** 

*Произведено шифрование признаков персональных данных путём матричного умножения матрицы объекты-признаки на случайно сгенерированную квадратную матрицу-ключ размерностью по числу признаков. Таким образом, получили зашифрованную матрицу объекты-признаки.*

*Качество предсказания страховых выплат у исходных и шифрованных данных на модели линейной регрессии получилось одинаковое (идентичные векторы предсказаний и одинаковые метрики коэффициента детерминации R2).*

*Для подтверждения гипотезы о равенстве предсказаний по исходным и шифрованным данным проведено математическое доказательство тождества $XP w' = X w$ , где $X$ - исходные данные, $XP$ - зашифрованные данные, $w$ и $w'$  - веса линейной регрессии по исходным и зашифрованным данным соответственно.*


**Задача 3 "Построение алгоритма преобразования исходных данных"** 

*Алгоритм шифрования исходных данных, с проверкой качества линейной регрессии, включает в себя следующие действия:*

    - генерация или ручное составление квадратной матрицы размерностью в число признаков
    
    - проверка матрицы на обратимость
    
    - матричное умножение датасета объекты-признаки на сгенерированную матрицу
    
    - разделение зашифрованных данных на обучающую-тестовую выборки, запуск модели линейной регрессии, вывод предсказаний и метрики точности предсказаний
    
    - разделение незашифрованных данных на обучающую-тестовую выборки по тем же объектам, что и у зашифрованных данных, запуск модели линейной регрессии, вывод предсказаний и метрики точности предсказаний
    
    - сравнение предсказаний и метрик у шифрованных и нешифрованных данных
    
    - декодирование данных


**Задача 4 "Проверка алгоритма на модели линейной регресии"** 

*В результате реализации вышеизложенного алгоритма на модели линейной регрессии из библиотеки sklearn предсказания и метрики у шифрованных и нешифрованных данных получились идентичными.*

*Шифрование методом матричного умножения исходных признаков на сгенерированную обратимую матрицу признано корректным.*

## Чек-лист проверки


<div class="alert alert-success">
<font size="5"><b>Комментарий ревьюера</b></font>

Успех 👍:


Евгений, здорово что в конце расписана все этапы работы. Это важно потому что когда проект захочет посмотреть будущий работодатель (или начальник), у него может не быть времени на подробный разбор кода. Вероятнее всего он бегло просмотрит код, а из общего вывода захочет получить представление о всей работе.



</div>




<div class="alert alert-info">
<font size="5"><b>Комментарий ревьюера</b></font>


Евгений, у тебя старательно выполненная работа, все четко, осмысленно. Отмечаю уровень твоей программистской подготовки.  Нет проблем с комментированием кода,





Я оставил небольшие советы и вопросики (если есть время и желание можешь воспользоваться/ответить)
    


Обязательное к исправлению:



    
- дорабатываем теоретическое доказательство, с учетом моих комментариев   


Жду исправлений, для принятия проекта. Если какие то вопросы, то сразу спрашивай ) 

</div>




<div class="alert alert-info">
<font size="5"><b>Комментарий ревьюераV2</b></font>

Спасибо за работу!    

    

Красного нет, вопросов нет, значит все, пора принимать) Надеюсь мои советы и вопросики были полезны и в копилочку знаний упало что то новое, а проект стал лучше, и симпатичней.

  
Отличная работа Евгений. Желаю успехов в дальнейшей учебе!





</div>

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования